spring.application.name=burmalda-bot-runtime
telegram.token=${MANAGER_BOT_TOKEN}
kie.callback-url=${AI_CALLBACK_URL}
kie.api.storage.base-url=${AI_STORAGE_URL}
kie.api.key=${AI_API_KEY}
kie.api.ai.base-url=${AI_API_BASE_URL}
# Database Connection Settings
spring.datasource.url=${SQL_LINK}
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false