spring.application.name=burmaldaBot
telegram.token=${MANAGER_BOT_TOKEN}
kie.callback-url=${AI_CALLBACK_URL}
kie.api.storage.base-url=${AI_STORAGE_URL}
kie.api.key=${AI_API_KEY}
kie.api.ai.base-url=${AI_API_BASE_URL}
# Database Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false