spring.application.name=burmalda-bot-manager
telegram.manager.token=${MANAGER_BOT_TOKEN}
telegram.manager.username=${MANAGER_BOT_USERNAME}
telegram.managed.adjective=${MANAGED_BOT_ADJECTIVE}
telegram.managed.noun=${MANAGED_BOT_NOUN}
telegram.managed.webhook=${RUNTIME_WEBHOOK_BASE_URL}
# Database Connection Settings
spring.datasource.url=${SQL_LINK}
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false