spring.application.name=burmalda-bot-manager
telegram.manager.token=${MANAGER_BOT_TOKEN}
telegram.manager.username=${MANAGER_BOT_USERNAME}
telegram.managed.adjective=${MANAGED_BOT_ADJECTIVE}
telegram.managed.noun=${MANAGED_BOT_NOUN}
telegram.managed.webhook=${RUNTIME_WEBHOOK_BASE_URL}
# Database Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false